del3/catalog/urls.py
from django.conf.urls import url
from . import views as catalog_views

urlpatterns = [
    url(r'^$', catalog_views.index, name='index'),
    url(r'^addtocart/(?P<product_id>[0-9]+)/$', catalog_views.add_to_cart, name='add_to_cart'),
    url(r'^add/$', catalog_views.add_product, name='add_product'),
    url(r'^delete/(?P<product_id>[0-9]+)/$', catalog_views.delete_product, name='delete_product'),
]

del3/del3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views as del3_views

urlpatterns = [
	url(r'^$', del3_views.index, name='index'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^catalog/', include('catalog.urls', namespace='catalog')),
	url(r'^agents/', include('agents.urls', namespace='agents')),
	url(r'^customers/', include('customers.urls', namespace='customers')),
	url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^cart/', del3_views.cart, name='cart'),
    url(r'^deletecartentry/(?P<content_id>[0-9]+)/$', del3_views.delete_cart_entry, name='delete_cart_entry'),
	url(r'^checkout/', del3_views.checkout, name='checkout'),
	url(r'^signup/', del3_views.signup, name='signup'),
	url(r'^signupagent/', del3_views.signup_agent, name='signup_agent'),
	url(r'^setpasswords/', del3_views.set_passwords, name='set_passwords'),
	url(r'^login/', del3_views.login, name='login'),
	url(r'^logout/', del3_views.logout, name='logout'),
]

del3/catalog/models.py
from django.db import models
from catalog.choices import COLOR_CHOICES

class Product(models.Model):
	product_id = models.AutoField(primary_key=True)
	name = models.CharField(max_length=255, blank=False, null=False, default='Swiffer')
	color = models.CharField(choices=COLOR_CHOICES, max_length=255, blank=False, null=False, default='red')
	quantity_stocked = models.PositiveIntegerField(blank=False, null=False, default=1)
	personalization_limit = models.IntegerField(blank=False, null=False, default=8)
	price = models.FloatField(blank=False, null=False, default=20.00)

	def __str__(self):
		return str(self.product_id)

	class Meta:
		app_label = 'catalog'
		db_table = 'product'

class Feature(models.Model):
	feature_id = models.AutoField(primary_key=True)
	product_id = models.ForeignKey(Product, db_column='product_id', null=False, default=1)
	feature_desc = models.CharField(max_length=255, blank=False, null=False, default='')

	def __str__(self):
		return str(self.product_id)

	class Meta:
		app_label = 'catalog'
		db_table = 'feature'

del3/catalog/forms.py
from django import forms
from catalog.models import Product, Feature
from catalog.choices import COLOR_CHOICES

class ProductForm(forms.Form):
	name = forms.CharField(max_length=250, required=True, help_text='Required')
	color = forms.ChoiceField(choices=COLOR_CHOICES)
	quantity_stocked = forms.IntegerField(min_value=1, max_value=99)
	personalization_limit = forms.IntegerField(min_value=0)
	price = forms.DecimalField(decimal_places=2, max_digits=11, required=True)
	features = forms.CharField(widget=forms.Textarea)

	class Meta:
		model = Product
		fields = ('name', 'color', 'quantity_stocked', 'personalization_limit', 'price')


	def save(self, commit=False):
		try:
			product = Product.objects.get(name=self.cleaned_data.get('name').title(), color = self.cleaned_data.get('color'))
			return product
		except Product.DoesNotExist:
			product = Product()
		product.name = self.cleaned_data.get('name').title()
		product.color = self.cleaned_data.get('color')
		product.quantity_stocked = self.cleaned_data.get('quantity_stocked')
		product.personalization_limit = self.cleaned_data.get('personalization_limit')
		product.price = self.cleaned_data.get('price')
		features = self.cleaned_data.get('features')
		product.save()
		for feature in features.splitlines():
			Feature(product_id=product, feature_desc=feature.strip()).save()
		return product

class AddCartForm(forms.Form):
	quantity = forms.IntegerField(min_value = 1, max_value=99)
	personalization = forms.CharField(max_length=255, required=False)

	class Meta:
		model = Product
		fields = ('quantity', 'personalization')

del3/catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.forms.formsets import formset_factory
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.admin.views.decorators import staff_member_required

from .models import Product, Feature
from orders.models import OrderInfo, Content
from customers.models import Customer
from agents.models import Agent

from .forms import ProductForm, AddCartForm

def index(request, product_id=None):
	product_list = Product.objects.all()
	product_selected = Product.objects.all().values('name').distinct()
	product_colors = {}
	feature_list = Feature.objects.all()
	for product in product_selected:
		colors = []
		for pr in Product.objects.filter(name=product["name"]):
			colors.append(pr.color)
		product_colors[product["name"]] = colors
	attribs = Product._meta.fields
	try:
		agent = Agent.objects.get(agent_id=request.user.pk)
		is_agent=True
	except Agent.DoesNotExist:
		is_agent=False
		if not is_agent:
			try:
				customer = Customer.objects.get(customer_id=request.user.pk)
			except Customer.DoesNotExist:
				is_agent=False
	form = AddCartForm()
	return render(request, 'catalog/index.html', {'form': form,
												'is_agent': is_agent,
												'product_colors': product_colors, 
												'product_selected': product_selected, 
												'product_list': product_list, 
												'attribs': attribs,
												'feature_list': feature_list})


def add_to_cart(request, product_id):
	if request.user.is_authenticated():
		if request.method == 'POST' and request.user.is_authenticated():
			form = AddCartForm(request.POST)
			if form.is_valid():
				quantity = form.cleaned_data.get('quantity')
				personalization = form.cleaned_data.get('personalization')

				product = Product.objects.get(pk=product_id)
				curr_customer = Customer.objects.get(customer_id=request.user.id)
				orders = OrderInfo.objects.filter(customer_id=request.user.id)
				
				if len(personalization) > product.personalization_limit:
					warning = "Over personalization limit"
					product_list = Product.objects.all()
					attribs = Product._meta.fields
					form = AddCartForm()
					return render(request, 'catalog/index.html', {'form': form, 'product_list': product_list, 'attribs': attribs, 'warning': warning})
			
				if quantity <= 99:
					if len(orders) == 0:  # If no current cart
						#make a new cart
						cart = create_cart(curr_customer)
						#add the product to it
						contents = insert_contents(cart, product, quantity, personalization)
						return HttpResponseRedirect(reverse('catalog:index'))
					elif len(orders) > 0:  # if there is existing cart or orders
						x = OrderInfo.objects.filter(delivery_time=None, cart_ready=False)
						y = set(orders).intersection(set(x))
						if len(y) > 0:  # if there is existing cart
							contents = insert_contents(y.pop(), product, quantity, personalization)
							return HttpResponseRedirect(reverse('catalog:index'))
						else:
							cart = create_cart(curr_customer)
							contents = insert_contents(cart, product, quantity, personalization)
							return HttpResponseRedirect(reverse('catalog:index'))
				else:
					warning = "Please choose below 99"
					product_list = Product.objects.all()
					attribs = Product._meta.fields
					return render(request, 'catalog/index.html', {'product_list': product_list, 'attribs': attribs, 'warning': warning})
			else:
				return HttpResponseRedirect(reverse('catalog:index'))
		else:
			return HttpResponseRedirect(reverse('catalog:index'))
	else:
		return HttpResponseRedirect(reverse('signup'))



def create_cart(customer):
	cart = OrderInfo()
	cart.agent_id = customer.agent_id
	cart.customer_id = customer
	cart.issue_date = None
	cart.issue_time = None
	cart.delivery_date = None
	cart.delivery_time = None
	cart.save()
	return cart

def insert_contents(cart, product, qty, prsn):
	try:
		contents = Content.objects.get(order_id=cart, product_id=product)
		if contents.quantity_ordered + qty > 99:
			pass
		else:
			contents.quantity_ordered += qty
	except Content.DoesNotExist:
		contents = Content()
		contents.order_id = cart
		contents.product_id = product
		contents.quantity_ordered = qty
		contents.discount = 0.00
	contents.personalization = prsn
	contents.save()
	return contents

def add_product(request):
	if request.user.is_staff:
		if request.method == 'POST':
			form = ProductForm(request.POST)
			if form.is_valid():
				product = form.save()
				return HttpResponseRedirect(reverse('catalog:index'))
			else:
				return render(request, 'catalog/addproduct.html', {'form': form})
		else: 
			form = ProductForm()
			return render(request, 'catalog/addproduct.html', {'form': form})
	else:
		return HttpResponseRedirect(reverse('catalog:index'))


@staff_member_required
def delete_product(request, product_id):
	product = Product.objects.get(pk=product_id)
	product.delete()
	return HttpResponseRedirect(reverse('catalog:index'))

del3/catalog/templates/catalog/addproduct.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Product</title>
	<style>
		table, th, td {
			border: 1px solid black;
		}
	</style>
</head>
<body>
	{% extends 'del3/base.html' %}
	{% block content %}
	<form action="{% url 'catalog:add_product' %}" method="post" class="navbar-form navbar-left" autocomplete="off" role="presentation">
		<h1 class="mp0">Add Product</h1>
		{% csrf_token %}
		{% for field in form %}
	      <p>
	        {{ field.label_tag }}<br>
	        {{ field }}
	        {% if field.help_text %}
	          <small style="color: grey">{{ field.help_text }}</small>
	        {% endif %}
	        {% for error in field.errors %}
	          <p style="color: red">{{ error }}</p>
	        {% endfor %}
	      </p>
	    {% endfor %}
	    {% if warning %}
	    <p>{{warning}}</p>
	    {% endif %}
	
	    {% for feature in formset %}
	    	<p>{{feature.as_table}}</p>
	    {% endfor %}
	    <button type="submit" class="btn-primary">Submit</button>
	</form>
	{% endblock %}
</body>
</html>

del3/catalog/templates/catalog/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Catalog</title>	<style>
		table, th, td {
			border: 1px solid black;
		}
	</style>
</head>
<body>
	{% extends 'del3/base.html' %}
	{% load static %}
	{% load verbose_names %}
	{% block content %}
	<div class="container">
	{% if user.is_staff or is_agent %}
	<h1 class="mbot0 garamond text-center">Product List</h1>
	{% if user.is_staff %}
	<a class="mp0" href='/catalog/add'>Add a product</a>
	{% endif %}
	<table class="table table-responsive table-striped">
		<tr>
			{% for attrib in attribs %}
			<th>{% get_verbose_field attrib.name %}</th>
			{% endfor %}
			{% if user.is_staff %}
			<th>Delete</th>
			{% endif %}
		</tr>
		{% for product in product_list %}
		<tr>
			<td>{{product.product_id}}</td>
			<td>{{product.name}}</td>
			<td>{{product.color}}</td>
			<td>{{product.quantity_stocked}}</td>
			<td>{{product.personalization_limit}}</td>
			<td>{{product.price}}</td>
			{% if user.is_staff %}
				<td class="text-center"><a href="{% url 'catalog:delete_product' product_id=product.pk %}">X</a></td>
			{% endif %}
		</tr>
		{% endfor %}
	</table>


		{% if warning %}
		<p>{{warning}}</p>
	</div>
	{% endif %}
	{% endif %}
	{% if not user.is_staff and not is_agent%}
	<h1 class="mbot10 garamond text-center">Product List</h1>
	{% if warning %}
		<p>&nbsp;&nbsp;&nbsp;&nbsp;{{warning}}</p>
	{% endif %}
	<div class="container">
		<div class="row">
		{% for product in product_list %}
			<div class="col-md-4">
				<img src="http://www.thecoloringshop.com/wp-content/uploads/2015/12/All-Star-Hardcover-Notebook-for-Gift-Stationery-diary-color-page-notepad-with-Metal-Cover-3.jpg" width="300px"></img>
				<p class="mp0"><b>{{product.name}}</b></p>
				<p class="mp0">Php {{product.price}}</p>
				<p class="mp0">{{product.color}}</p>
				<p class="mp0">Personalization limit: {{product.personalization_limit}} characters</p>
				<p class="mp0">Features:</p>
				{% for feature in feature_list %}
				{% if feature.product_id == product %}
				<p class="mp0">&nbsp;&nbsp;{{feature.feature_desc}}</p>
				{% endif %}
				{% endfor %}

				<form action="{% url 'catalog:add_to_cart' product_id=product.pk %}" id='{{forloop.counter}}' class="navbar-left" method="post" autocomplete="off" role="presentation">
				{% csrf_token %}
				{% for field in form %}
					<p>
					{{ field.label_tag }}<br>
					{{ field }}
					{% if field.help_text %}
					<small style="color: grey">{{ field.help_text }}</small>
					{% endif %}
					{% for error in field.errors %}
					<p style="color: red">{{ error }}</p>
					{% endfor %}
					</p>
				{% endfor %}
				<button class="btn-primary" onclick="document.getElementById('{{forloop.counter}}').submit();">Add to Cart</a>
				</form>
			</div>
			{% if forloop.counter|divisibleby:3 %}
		</div>
		<div class="row mtop50">
			{% endif %}
		{% endfor %}
		</div>
	
	</div>
	{% endif %}
	{% endblock %}
</body>
</html>