del3/del3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views as del3_views

urlpatterns = [
	url(r'^$', del3_views.index, name='index'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^catalog/', include('catalog.urls', namespace='catalog')),
	url(r'^agents/', include('agents.urls', namespace='agents')),
	url(r'^customers/', include('customers.urls', namespace='customers')),
	url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^cart/', del3_views.cart, name='cart'),
    url(r'^deletecartentry/(?P<content_id>[0-9]+)/$', del3_views.delete_cart_entry, name='delete_cart_entry'),
	url(r'^checkout/', del3_views.checkout, name='checkout'),
	url(r'^signup/', del3_views.signup, name='signup'),
	url(r'^signupagent/', del3_views.signup_agent, name='signup_agent'),
	url(r'^setpasswords/', del3_views.set_passwords, name='set_passwords'),
	url(r'^login/', del3_views.login, name='login'),
	url(r'^logout/', del3_views.logout, name='logout'),
]

del3/orders/urls.py
from django.conf.urls import url

from . import views as order_views

urlpatterns = [
    url(r'^$', order_views.index, name='index'),
    url(r'^approve/(?P<order_id>[0-9]+)/$', order_views.approve_order, name='approve_order'),
]

del3/orders/models.py
from django.db import models

from agents.models import Agent
from catalog.models import Product
from customers.models import Customer

class Recipient(models.Model):
	recipient_id = models.AutoField(primary_key=True)
	first_name = models.CharField(max_length=255, blank=False, null=False, default='Ruscie')
	last_name = models.CharField(max_length=255, blank=False, null=False, default='Pient')
	street = models.CharField(max_length=255, blank=False, null=False, default='Shiny Street')
	city = models.CharField(max_length=255, blank=False, null=False, default='Clean City')
	country = models.CharField(max_length=255, blank=False, null=False, default='Cool Country')

	def __str__(self):
		return str(self.recipient_id)

	class Meta:
		app_label = 'orders'
		db_table = 'recipient'


class OrderInfo(models.Model):
	order_id = models.AutoField(primary_key=True, unique=True)
	agent_id = models.ForeignKey(Agent, db_column='agent_id', null=False, blank=False, default=2)
	customer_id = models.ForeignKey(Customer, db_column='customer_id', null=False, blank=False, default=4)
	issue_date = models.DateField(blank=False, null=False, default='2017-01-01')
	issue_time = models.TimeField(blank=False, null=False, default='12:00:00')
	delivery_date = models.DateField(blank=False, null=False, default='2017-01-01')
	delivery_time = models.TimeField(blank=False, null=False, default='12:00:00')	
	cart_ready = models.BooleanField(blank=False, null=False, default=0)

	def __str__(self):
		return str(self.order_id)

	class Meta:
		ordering = ['order_id', 'customer_id']
		app_label = 'orders'
		db_table = 'orderinfo'

class Content(models.Model):
	content_id = models.AutoField(primary_key=True, unique=True)
	order_id = models.ForeignKey(OrderInfo, db_column='order_id')
	product_id = models.ForeignKey(Product, db_column='product_id')
	personalization = models.CharField(max_length=255, blank=False, null=False, default='')
	quantity_ordered = models.PositiveIntegerField(blank=False, null=False, default=1)
	discount = models.FloatField(blank=False, null=False, default=0.00)

	def __str__(self):
		return str(self.content_id)

	class Meta:
		ordering = ['order_id', 'product_id']
		app_label = 'orders'
		db_table = 'content'

class Delivery(models.Model):
	delivery_id = models.AutoField(primary_key=True, unique=True)
	order_id = models.OneToOneField(OrderInfo, db_column='order_id', unique=True)
	recipient_id = models.ForeignKey(Recipient, db_column='recipient_id', null=True, blank=False, default=None)
	gift = models.BooleanField(blank=False, null=False, default=0)

	def __str__(self):
		return str(self.delivery_id)

	class Meta:
		ordering = ['order_id']
		app_label = 'orders'
		db_table = 'delivery'

del3/orders/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from .models import OrderInfo, Content, Delivery
from agents.models import Agent
from catalog.models import Product
from customers.models import Customer
from datetime import datetime
def index(request):
	try:
		agent = Agent.objects.get(agent_id=request.user.pk)
		order_list = OrderInfo.objects.filter(agent_id=agent)
		content_list = Content.objects.filter(order_id__in=order_list)
		delivery_list = Delivery.objects.filter(order_id__in=order_list)
		order_attribs = OrderInfo._meta.fields
		content_attribs = Content._meta.fields
		is_agent = True
		return render(request, 'orders/index.html', {'is_agent': is_agent, 'order_list': order_list, 'order_attribs': order_attribs,
		'content_list': content_list, 
		'delivery_list': delivery_list,
		'content_attribs': content_attribs})
	except Agent.DoesNotExist:
		is_agent = False
	try:
		customer = Customer.objects.get(customer_id=request.user.pk)
		order_list = OrderInfo.objects.filter(customer_id=request.user.pk)
		content_list = Content.objects.filter(order_id__in=order_list)
		delivery_list = Delivery.objects.filter(order_id__in=order_list)
	except Customer.DoesNotExist:
		order_list = OrderInfo.objects.all()
		content_list = Content.objects.all()
		delivery_list = Delivery.objects.all()
	order_attribs = OrderInfo._meta.fields
	content_attribs = Content._meta.fields
	return render(request, 'orders/index.html', {'is_agent': is_agent, 'order_list': order_list, 'order_attribs': order_attribs,
		'content_list': content_list, 
		'delivery_list': delivery_list,
		'content_attribs': content_attribs})

def approve_order(request, order_id):
	try:
		agent = Agent.objects.get(pk=request.user.id)
		order = OrderInfo.objects.get(order_id=order_id)
		content = Content.objects.filter(order_id=order.order_id)
		content_products = Content.objects.filter(order_id=order.order_id).values('product_id')
		product = Product.objects.filter(product_id__in=content_products)
		for item in content:
			if item.quantity_ordered <= item.product_id.quantity_stocked:
				all_good = True
			else:
				all_good = False
		if order.cart_ready is True and all_good is True:
			order.issue_date = datetime.today()
			order.issue_time = datetime.now().time()
			order.delivery_date = datetime.today()
			order.delivery_time = datetime.now().time()
			order.save()
			agent.total_transactions += 1
			agent.save()
			for item in content:
				product = Product.objects.get(product_id=item.product_id.pk)
				product.quantity_stocked -= item.quantity_ordered
				product.save()
			return HttpResponseRedirect(reverse('orders:index'))
		else:
			return HttpResponseRedirect(reverse('orders:index'))
	except Agent.DoesNotExist:
		return HttpResponseRedirect(reverse('orders:index'))

del3/orders/templates/orders/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Orders</title>

	<style>
		table, th, td {
			border: 1px solid black;
		}
	</style>
</head>
<body>
	{% extends 'del3/base.html' %}
	{% load verbose_names %}
	{% block content %}
	{% if request.user.is_staff %}
	<div class="container">
	<h1 class="garamond text-center">Order List</h1>
	<table class="table table-responsive table-striped">
		<tr>
			{% for attrib in order_attribs|slice:":3" %}
			<th>{% get_verbose_field attrib.name %}</th>
			{% endfor %}
			<th>Recipient</th>
			<th>Recipient Name</th>
			{% for attrib in order_attribs|slice:"3:7" %}
			<th>{% get_verbose_field attrib.name %}</th>
			{% endfor %}
			<th>Summary</th>
		</tr>
		{% for order in order_list %}
		{% if order.issue_date != None %}
		<tr>
			<td>{{order.order_id}}</td>
			<td>{{order.agent_id.pk}}</td>
			<td >{{order.customer_id.pk}}</td>
			
			{% for delivery in delivery_list %}
			{% if order.pk == delivery.pk %}
			<td>{{delivery.recipient_id}}</td>
			<td>{{delivery.recipient_id.first_name}} {{delivery.recipient_id.last_name}}</td>
			{% endif %}
			{% endfor %}
			
			<td>{{order.issue_date}}</td>
			<td>{{order.issue_time}}</td>
			<td>{{order.delivery_date}}</td>
			<td>{{order.delivery_time}}</td>

			{% for delivery in delivery_list %}
			{% if order.pk == delivery.pk %}
			<td>Agent {{order.agent_id}} {{order.agent_id.first_name}} has approved Order {{order.order_id}} sent to Recipient {{delivery.recipient_id}} {{delivery.recipient_id.first_name}}</td>
			{% endif %}
			{% endfor %}
				
		</tr>
		{% endif %}
		{% endfor %}
	</table>

	<h1 class="garamond text-center">Order Contents</h1>
	<table class="table table-responsive table-striped">
		<tr>
			{% for content_attrib in content_attribs|slice:"1:3" %}
			<th>{% get_verbose_field content_attrib.name %}</th>
			{% endfor %}
			<th>Product Name</th>
			<th>Color</th>
			{% for content_attrib in content_attribs|slice:"3:" %}
			<th>{% get_verbose_field content_attrib.name %}</th>
			{% endfor %}
		</tr>
		{% for content in content_list %}
		{% if content.order_id.cart_ready == True and content.order_id.issue_date %}
		<tr>
			<td>{{content.order_id}}</td>
			<td>{{content.product_id}}</td>
			<td>{{content.product_id.name}}</td>
			<td>{{content.product_id.color}}</td>
			<td>{{content.personalization}}</td>
			<td>{{content.quantity_ordered}}</td>
			<td>{{content.discount}}</td>
		</tr>
		{% endif %}
		{% endfor %}
	</table>

	<h1 class="garamond text-center">Pending Order List</h1>
	<table class="table table-responsive table-striped">
		<tr>
			{% for attrib in order_attribs|slice:":3" %}
			<th>{{attrib.name}}</th>
			{% endfor %}
			<th>recipient</th>
			{% for attrib in order_attribs|slice:"7:7" %}
			<th>{{attrib.name}}</th>
			{% endfor %}
			<th>summary</th>
		</tr>
		{% for order in order_list %}
		{% if order.issue_date == None and order.cart_ready %}
		<tr>
			<td>{{order.order_id}}</td>
			<td>{{order.agent_id}}</td>
			<td >{{order.customer_id.pk}}</td>
			
			{% for delivery in delivery_list %}
			{% if order.pk == delivery.pk %}
			<td>{{delivery.recipient_id}}</td>
			{% endif %}
			{% endfor %}

			{% for delivery in delivery_list %}
			{% if order.pk == delivery.pk %}
			<td>Agent {{order.agent_id}} {{order.agent_id.first_name}} has not accepted Order {{order.order_id}} to be sent to Recipient {{delivery.recipient_id}} {{delivery.recipient_id.first_name}}</td>
			{% endif %}
			{% endfor %}
				
		</tr>
		{% endif %}
		{% endfor %}
	</table>

	<h1 class="garamond text-center">Pending Contents</h1>
	<table class="table table-responsive table-striped">
		<tr>
			{% for content_attrib in content_attribs|slice:"1:3" %}
			<th>{% get_verbose_field content_attrib.name %}</th>
			{% endfor %}
			<th>Product Name</th>
			<th>Color</th>
			{% for content_attrib in content_attribs|slice:"3:" %}
			<th>{% get_verbose_field content_attrib.name %}</th>
			{% endfor %}
		</tr>
		{% for content in content_list %}
		{% if content.order_id.cart_ready == True and not content.order_id.issue_date %}
		<tr>
			<td>{{content.order_id}}</td>
			<td>{{content.product_id}}</td>
			<td>{{content.product_id.name}}</td>
			<td>{{content.product_id.color}}</td>
			<td>{{content.personalization}}</td>
			<td>{{content.quantity_ordered}}</td>
			<td>{{content.discount}}</td>
		</tr>
		{% endif %}
		{% endfor %}
	</div>
	{% elif request.user.is_authenticated %}
	<div class="container">
		<h1 class="garamond text-center">Your Delivered Orders</h1>
		<table class="table table-responsive table-striped">
		<tr>
			{% for attrib in content_attribs|slice:"1:3" %}
			<th>{% get_verbose_field attrib.name %}</th>
			{% endfor %}
			<th>Product Name</th>
			<th>Color</th>
			{% for attrib in content_attribs|slice:"3:" %}
			<th>{% get_verbose_field attrib.name %}</th>
			{% endfor %}
		</tr>
		{% for content in content_list %}
		{% if content.order_id.cart_ready == True and content.order_id.issue_date %}
		<tr>
			<td>{{content.order_id}}</td>
			<td>{{content.product_id}}</td>
			<td>{{content.product_id.name}}</td>
			<td>{{content.product_id.color}}</td>
			<td>{{content.personalization}}</td>
			<td>{{content.quantity_ordered}}</td>
			<td>{{content.discount}}</td>
		</tr>
		{% endif %}
		{% endfor %}
	</table>

	<h1 class="garamond text-center">Your Pending Orders</h1>
		<table class="table table-responsive table-striped">
		<tr>
			{% for attrib in content_attribs|slice:"1:3" %}
			<th>{% get_verbose_field attrib.name %}</th>
			{% endfor %}
			<th>Product Name</th>
			<th>Color</th>
			{% for attrib in content_attribs|slice:"3:" %}
			<th>{% get_verbose_field attrib.name %}</th>
			{% endfor %}
			{% if is_agent %}
			<th>Approve Order</th>
			{% endif %}
		</tr>
		{% for content in content_list %}
		{% if content.order_id.cart_ready == True and not content.order_id.issue_date %}
		<tr>
			<td>{{content.order_id}}</td>
			<td>{{content.product_id}}</td>
			<td>{{content.product_id.name}}</td>
			<td>{{content.product_id.color}}</td>
			<td>{{content.personalization}}</td>
			<td>{{content.quantity_ordered}}</td>
			<td>{{content.discount}}</td>
			{% if is_agent %}
			<td class="text-center"><a class="text-center" href="{% url 'orders:approve_order' order_id=content.order_id.pk %}">X</a></td>
			{% endif %}
		</tr>
		{% endif %}
		{% endfor %}
	</table>
	</div>
	{% endif %}
	{% endblock %}
</body>
</html>