del3/agents/urls.py
from django.conf.urls import url

from . import views as agents_views


urlpatterns = [
    url(r'^$', agents_views.index, name='index'),
    url(r'^generate/$', agents_views.generate, name='generate'),
]

del3/del3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views as del3_views

urlpatterns = [
	url(r'^$', del3_views.index, name='index'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^catalog/', include('catalog.urls', namespace='catalog')),
	url(r'^agents/', include('agents.urls', namespace='agents')),
	url(r'^customers/', include('customers.urls', namespace='customers')),
	url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^cart/', del3_views.cart, name='cart'),
    url(r'^deletecartentry/(?P<content_id>[0-9]+)/$', del3_views.delete_cart_entry, name='delete_cart_entry'),
	url(r'^checkout/', del3_views.checkout, name='checkout'),
	url(r'^signup/', del3_views.signup, name='signup'),
	url(r'^signupagent/', del3_views.signup_agent, name='signup_agent'),
	url(r'^setpasswords/', del3_views.set_passwords, name='set_passwords'),
	url(r'^login/', del3_views.login, name='login'),
	url(r'^logout/', del3_views.logout, name='logout'),
]

del3/agents/models.py
from django.db import models
from django.contrib.auth.models import User

class Agent(models.Model):
	agent_id = models.OneToOneField(User, db_column='agent_id', primary_key=True)
	total_transactions = models.PositiveIntegerField(blank=False, null=False, default=0)

	class Meta:
		app_label = 'agents'
		db_table = 'agent'

	def __str__(self):
		return str(self.agent_id)

del3/agents/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User

from .models import Agent
from del3.models import Invite
from orders.models import OrderInfo

import random
from datetime import datetime


def index(request):
	agent_list = Agent.objects.all()
	attribs = Agent._meta.fields
	codes = Invite.objects.all()
	try:
		agent = Agent.objects.get(agent_id=request.user.id)
		show_button = True
		return render(request, 'agents/index.html', {'codes': codes, 'show_button': show_button,'agent_list': agent_list, 'attribs': attribs})
	except Agent.DoesNotExist:
		return render(request, 'agents/index.html', {'codes': codes, 'agent_list': agent_list, 'attribs': attribs})

@staff_member_required
def generate(request):
	check = False
	while not check:
		code = random.randint(1, 100)
		try:
			Invite.objects.get(invite_code=code)
		except Invite.DoesNotExist:
			check = True
	invite = Invite(invite_code=code, used=False)
	invite.save()
	return HttpResponseRedirect(reverse("agents:index"))

del3/agents/templates/agents/approve.html
<!DOCTYPE html>
<html>
<head>
	<title>Agents</title>
	<style>
		table, th, td {
			border: 1px solid black;
		}
	</style>
</head>
<body>
	{% extends 'del3/base.html' %}

	{% block content %}
	<h1>Carts pending</h1>
	<table>
		<tr>
			{% for attrib in attribs|slice:":3" %}
			<th>{{attrib.name}}</th>
			{% endfor %}
		</tr>
		{% for order in order_list %}
		<tr>
			<td>{{order.order_id}}</td>
			<td>{{order.agent_id}}</td>
			<td>{{order.customer_id}}</td>
		</tr>
		{% endfor %}
	</table>
	{% endblock %}
</body>
</html>

del3/agents/templates/agents/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Agents</title>
	<style>
		table, th, td {
			border: 1px solid black;
		}
	</style>
</head>
<body>
	{% extends 'del3/base.html' %}
	{% load verbose_names %}
	{% load static %}
	{% block content %}
	{% if not user.is_staff %}
	<h1 class="mp3">AGENT LIST</h1>
	<div class="container mtop60">

	
		<div class="row mp10">
		{% for agent in agent_list %}
			<div class="col-md-2 mp11">
				<img width="100px" height="100px" class="agentimage" src="{% static 'css/person-icon.png' %}" alt="Agent Image"></img>
			</div>
			<p></p>
			<div class="col-md-10">
				<p class="mp1">{{agent.agent_id.first_name}} {{agent.agent_id.last_name}}</p>
				<p class="mp2">Agent ID: {{agent.agent_id.id}}</p>
				<p class="mp2">Total Transactions: {{agent.total_transactions}}</p>
			</div>
			<hr>
		</div>
		<div class="row mtop50">
		{% endfor %}
		</div>
	</div>

	{% elif user.is_staff %}
	<h1 class="text-center garamond">Agent List</h1>
	<div class="container">
	<table class="table table-responsive table-striped">
		<tr>
			{% for attrib in attribs|slice:":1"%}
			<th>{% get_verbose_field attrib.name %}</th>
			{% endfor %}
			<th>First Name</th>
			<th>Last Name</th>
			{% for attrib in attribs|slice:"1:"%}
			<th>{% get_verbose_field attrib.name %}</th>
			{% endfor %}
		</tr>
		{% for agent in agent_list %}
		<tr>
			<td>{{agent.agent_id.id}}</td>
			<td>{{agent.agent_id.first_name}}</td>
			<td>{{agent.agent_id.last_name}}</td>
			<td>{{agent.total_transactions}}</td>
		</tr>
		{% endfor %}
	</table>
	<h1 class="mp0 text-center garamond">Code List</h1>
	<p class="mp0"><a href="{% url 'agents:generate' %}">Generate Code</a></p>
	<table class="table table-responsive table-striped">
	<tr>
		<th>Invite ID</th>
		<th>Code</th>
		<th>Used</th>
	</tr>
	{% for code in codes %}
	<tr>
		<td>{{code.invite_id}}</td>
		<td>{{code.invite_code}}</td>
		<td>{{code.used}}</td>
	</tr>
	{% endfor %}
	</table>
	{% endif %}
	
	{% if code %}
	<p>Generated code is: {{code}}. Please enter this code into the agent code field on the agent sign up page.</p>
	{% endif %}

	</div>
	{% endblock %}
</body>
</html>